import {spawn} from 'node:child_process';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const project=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const [entry,...args]=process.argv.slice(2);
if(!['start','test'].includes(entry))throw Error('Entry must be start or test');
const target=entry==='start'?'server.mjs':'scripts/test.mjs';
const child=spawn(process.execPath,[path.join(project,target),...args],{cwd:project,stdio:'inherit',windowsHide:true});
child.on('error',e=>{console.error(e.message);process.exitCode=2});
child.on('exit',code=>{process.exitCode=code??2});
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>{child.kill(signal)});
